services:
  pdflib.console:
    image: pdflib.console
    build:
      context: .
      dockerfile: PDFLib.Console/Dockerfile
  pdflib.benchmarks:
    image: pdflib-benchmarks
    build:
      context: .
      dockerfile: ./Benchmarks/Dockerfile
