services:
  pdflib.chromium:
    image: pdflib.chromium
    build:
      context: .
      dockerfile: PDFLib.Chromium/Dockerfile
  pdflib.benchmarks:
    image: pdflib-benchmarks
    build:
      context: .
      dockerfile: ./Benchmarks/Dockerfile
